// <auto-generated />
using System;
using Hospital.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hospital.Migrations
{
    [DbContext(typeof(HospitalContext))]
    [Migration("20210302084613_HospitalFacilities")]
    partial class HospitalFacilities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("Hospital.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("EMPLOYEE_ID");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)")
                        .HasColumnName("LAST_NAME");

                    b.Property<int>("SVNR")
                        .HasColumnType("INT")
                        .HasColumnName("SVNR");

                    b.Property<int>("Salary")
                        .HasColumnType("INT")
                        .HasColumnName("SALARY");

                    b.HasKey("EmployeeId");

                    b.HasIndex("SVNR")
                        .IsUnique();

                    b.ToTable("EMPLOYEES");
                });

            modelBuilder.Entity("Hospital.Models.HospitalFacility", b =>
                {
                    b.Property<int>("FacilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("FACILITY_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("NAME");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("PHONE_NR");

                    b.HasKey("FacilityId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("HOSPITAL_FACILITIES");
                });

            modelBuilder.Entity("Hospital.Models.CareTaker", b =>
                {
                    b.HasBaseType("Hospital.Models.Employee");

                    b.Property<int?>("SUPERVISOR_ID")
                        .HasColumnType("INT");

                    b.HasIndex("SUPERVISOR_ID");

                    b.ToTable("CARE_TAKERS");
                });

            modelBuilder.Entity("Hospital.Models.Physician", b =>
                {
                    b.HasBaseType("Hospital.Models.Employee");

                    b.Property<string>("JobSpecialisation")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)")
                        .HasColumnName("JOB_SPECIALISATION");

                    b.ToTable("PHYSICIANS");
                });

            modelBuilder.Entity("Hospital.Models.CareTaker", b =>
                {
                    b.HasOne("Hospital.Models.Employee", null)
                        .WithOne()
                        .HasForeignKey("Hospital.Models.CareTaker", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital.Models.CareTaker", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SUPERVISOR_ID");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("Hospital.Models.Physician", b =>
                {
                    b.HasOne("Hospital.Models.Employee", null)
                        .WithOne()
                        .HasForeignKey("Hospital.Models.Physician", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
